baseURL = 'https://antonylion.github.io/antonyzappacosta/'
languageCode = 'en-us'
title = ''
theme = "paper"


# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'plion98'               # twitter.com/YOUR_TWITTER_ID
  github = 'antonylion'                 # github.com/YOUR_GITHUB_ID

  avatar = 'antony.zappacosta@studio.unibo.it'
  name = 'Antony Zappacosta'
  bio = 'Software engineer'

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"