baseURL = 'https://antonylion.github.io/antonyzappacosta'
languageCode = 'en-us'
title = ''
theme = "paper"
publishDir = 'public'



[markup.goldmark.parser.attribute]
  block = true
  title = true

[markup.goldmark.renderer]
  hardWraps = false
  unsafe = true
  xhtml = true

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  github = 'YOUR_GITHUB_ID'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID

  # home page profile
  avatar = '/images/Antony.jpg'                 # gravatar email or image url
  name = 'Antony Zappacosta'
  bio = 'YOUR_BIO'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = true                               # enable KaTex math typesetting globally

[menu]

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 10
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/resume"
    weight = 10